"""Generated XDWAPI function signatures for SDK 9.1.7."""

import ctypes
from . import types as T

FUNCTION_SPECS = {
    'XDW_GetInformation': (ctypes.c_int32, (ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetInformationW': (ctypes.c_int32, (ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_void_p)),
    'XDW_AddSystemFolder': (ctypes.c_int32, (ctypes.c_int32, ctypes.c_void_p)),
    'XDW_MergeXdwFiles': (ctypes.c_int32, (ctypes.POINTER(ctypes.c_char_p), ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_MergeXdwFilesW': (ctypes.c_int32, (ctypes.POINTER(ctypes.POINTER(T.XDW_WCHAR)), ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_OpenDocumentHandle': (ctypes.c_int32, (ctypes.c_char_p, ctypes.POINTER(T.XDW_DOCUMENT_HANDLE), ctypes.POINTER(T.XDW_OPEN_MODE))),
    'XDW_OpenDocumentHandleW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_DOCUMENT_HANDLE), ctypes.POINTER(T.XDW_OPEN_MODE))),
    'XDW_CloseDocumentHandle': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p)),
    'XDW_GetDocumentInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_DOCUMENT_INFO))),
    'XDW_GetPageInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_PAGE_INFO))),
    'XDW_GetPageImage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetPageImageW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_GetPageText': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_ConvertPageToImageFile': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(T.XDW_IMAGE_OPTION))),
    'XDW_ConvertPageToImageFileW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_IMAGE_OPTION))),
    'XDW_GetPage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetPageW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_DeletePage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_RotatePage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SaveDocument': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p)),
    'XDW_CreateXdwFromImageFile': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(T.XDW_CREATE_OPTION))),
    'XDW_CreateXdwFromImageFileW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_CREATE_OPTION))),
    'XDW_GetOriginalDataInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_ORGDATA_INFO), ctypes.c_void_p)),
    'XDW_GetOriginalData': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetOriginalDataW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_InsertOriginalData': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_DeleteOriginalData': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_BeginCreationFromAppFile': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.POINTER(T.XDW_CREATE_HANDLE), ctypes.c_void_p)),
    'XDW_BeginCreationFromAppFileW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.POINTER(T.XDW_CREATE_HANDLE), ctypes.c_void_p)),
    'XDW_EndCreationFromAppFile': (ctypes.c_int32, (T.XDW_CREATE_HANDLE, ctypes.c_void_p)),
    'XDW_GetStatusCreationFromAppFile': (ctypes.c_int32, (T.XDW_CREATE_HANDLE, ctypes.POINTER(T.XDW_CREATE_STATUS))),
    'XDW_CancelCreationFromAppFile': (ctypes.c_int32, (T.XDW_CREATE_HANDLE, ctypes.c_void_p)),
    'XDW_GetUserAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetUserAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetAnnotationInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_ANNOTATION_INFO), ctypes.c_void_p)),
    'XDW_GetAnnotationAttribute': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_AddAnnotation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(T.XDW_AA_INITIAL_DATA), ctypes.POINTER(T.XDW_ANNOTATION_HANDLE), ctypes.c_void_p)),
    'XDW_RemoveAnnotation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_void_p)),
    'XDW_SetAnnotationAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetAnnotationSize': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetAnnotationPosition': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_CreateSfxDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_CreateSfxDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_ExtractFromSfxDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_ExtractFromSfxDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_ConvertPageToImageHandle': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(T.XDW_IMAGE_OPTION))),
    'XDW_GetThumbnailImageHandle': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p)),
    'XDW_GetPageTextToMemory': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetFullText': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetPageUserAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetPageUserAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_ReducePageNoise': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_ShowOrHideAnnotations': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetCompressedPageImage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetCompressedPageImageW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_InsertDocument': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_InsertDocumentW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_ApplyOcr': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_RotatePageAuto': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_CreateBinder': (ctypes.c_int32, (ctypes.c_char_p, ctypes.POINTER(T.XDW_BINDER_INITIAL_DATA), ctypes.c_void_p)),
    'XDW_CreateBinderW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_BINDER_INITIAL_DATA), ctypes.c_void_p)),
    'XDW_InsertDocumentToBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetDocumentFromBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetDocumentFromBinderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_DeleteDocumentInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetDocumentNameInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetDocumentNameInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetDocumentInformationInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_DOCUMENT_INFO), ctypes.c_void_p)),
    'XDW_Finalize': (ctypes.c_int32, (ctypes.c_void_p,)),
    'XDW_GetPageColorInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_PAGE_COLOR_INFO), ctypes.c_void_p)),
    'XDW_OptimizeDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_OptimizeDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_ProtectDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_ProtectDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_CreateXdwFromImageFileAndInsertDocument': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(T.XDW_CREATE_OPTION), ctypes.c_void_p)),
    'XDW_CreateXdwFromImageFileAndInsertDocumentW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_CREATE_OPTION), ctypes.c_void_p)),
    'XDW_GetDocumentAttributeNumber': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByName': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByOrder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetDocumentAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_SucceedAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SucceedAttributeW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetPageFormAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetPageFormAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_UpdatePageForm': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_RemovePageForm': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetLinkRootFolderInformation': (ctypes.c_int32, (ctypes.c_int32, ctypes.POINTER(T.XDW_LINKROOTFOLDER_INFO), ctypes.c_void_p)),
    'XDW_GetLinkRootFolderInformationW': (ctypes.c_int32, (ctypes.c_int32, ctypes.POINTER(T.XDW_LINKROOTFOLDER_INFOW), ctypes.c_void_p)),
    'XDW_GetLinkRootFolderNumber': (ctypes.c_int32, (ctypes.c_void_p,)),
    'XDW_GetLinkRootFolderNumberW': (ctypes.c_int32, (ctypes.c_void_p,)),
    'XDW_GetPageTextInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_GetDocumentSignatureNumber': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p)),
    'XDW_AddAnnotationOnParentAnnotation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(T.XDW_AA_INITIAL_DATA), ctypes.POINTER(T.XDW_ANNOTATION_HANDLE), ctypes.c_void_p)),
    'XDW_SignDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_SignDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_GetSignatureInformation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_UpdateSignatureStatus': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_GetOcrImage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_GetOcrImageW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p, ctypes.c_void_p)),
    'XDW_SetOcrData': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_OCR_TEXTINFO), ctypes.c_void_p)),
    'XDW_GetDocumentAttributeNumberInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByNameInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByOrderInBinder': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetTMInfo': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetTMInfo': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_void_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_CreateXdwFromImagePdfFile': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_FindTextInPage': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_char_p, ctypes.POINTER(T.XDW_FIND_TEXT_OPTION), ctypes.POINTER(T.XDW_FOUND_HANDLE), ctypes.c_void_p)),
    'XDW_FindNext': (ctypes.c_int32, (ctypes.POINTER(T.XDW_FOUND_HANDLE), ctypes.c_void_p)),
    'XDW_GetNumberOfRectsInFoundObject': (ctypes.c_int32, (T.XDW_FOUND_HANDLE, ctypes.c_void_p)),
    'XDW_GetRectInFoundObject': (ctypes.c_int32, (T.XDW_FOUND_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_RECT), ctypes.POINTER(ctypes.c_int32), ctypes.c_void_p)),
    'XDW_CloseFoundHandle': (ctypes.c_int32, (T.XDW_FOUND_HANDLE,)),
    'XDW_GetAnnotationUserAttribute': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_SetAnnotationUserAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_StarchAnnotation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_ReleaseProtectionOfDocument': (ctypes.c_int32, (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_ReleaseProtectionOfDocumentW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_GetProtectionInformation': (ctypes.c_int32, (ctypes.c_char_p, ctypes.POINTER(T.XDW_PROTECTION_INFO), ctypes.c_void_p)),
    'XDW_GetProtectionInformationW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_PROTECTION_INFO), ctypes.c_void_p)),
    'XDW_GetAnnotationCustomAttributeByName': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetAnnotationCustomAttributeByOrder': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetAnnotationCustomAttributeNumber': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.c_void_p)),
    'XDW_SetAnnotationCustomAttribute': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)),
    'XDW_GetPageTextToMemoryW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetFullTextW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
    'XDW_GetAnnotationAttributeW': (ctypes.c_int32, (T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_SetAnnotationAttributeW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_char_p, ctypes.c_int32, ctypes.c_void_p, ctypes.c_int32, ctypes.c_uint32, ctypes.c_int32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByNameW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByOrderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByNameInBinderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_GetDocumentAttributeByOrderInBinderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(ctypes.c_int32), ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_SetDocumentAttributeW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_void_p, ctypes.c_int32, ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_GetDocumentNameInBinderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_SetDocumentNameInBinderW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_GetOriginalDataInformationW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_ORGDATA_INFOW), ctypes.POINTER(ctypes.c_int32), ctypes.c_uint32, ctypes.c_void_p)),
    'XDW_AddAnnotationFromAnnFile': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_char_p, ctypes.c_int32, ctypes.c_int32, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(T.XDW_ANNOTATION_HANDLE), ctypes.c_void_p)),
    'XDW_AddAnnotationFromAnnFileW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_int32, ctypes.c_int32, T.XDW_ANNOTATION_HANDLE, ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(T.XDW_ANNOTATION_HANDLE), ctypes.c_void_p)),
    'XDW_GroupAnnotations': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, T.XDW_ANNOTATION_HANDLE, ctypes.POINTER(ctypes.c_int32), ctypes.c_int32, ctypes.POINTER(T.XDW_ANNOTATION_HANDLE), ctypes.c_void_p)),
    'XDW_UnGroupAnnotation': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, T.XDW_ANNOTATION_HANDLE, ctypes.c_void_p)),
    'XDW_OpenDocumentHandleEx': (ctypes.c_int32, (ctypes.c_char_p, ctypes.POINTER(T.XDW_DOCUMENT_HANDLE), ctypes.POINTER(T.XDW_OPEN_MODE))),
    'XDW_OpenDocumentHandleExW': (ctypes.c_int32, (ctypes.POINTER(T.XDW_WCHAR), ctypes.POINTER(T.XDW_DOCUMENT_HANDLE), ctypes.POINTER(T.XDW_OPEN_MODE))),
    'XDW_InsertOriginalDataW': (ctypes.c_int32, (T.XDW_DOCUMENT_HANDLE, ctypes.c_int32, ctypes.POINTER(T.XDW_WCHAR), ctypes.c_void_p)),
}

FUNCTION_COUNT = 141
