from __future__ import annotations

from enum import IntEnum

from ._raw import constants as C


class OpenMode(IntEnum):
    READONLY = C.XDW_OPEN_READONLY
    UPDATE = C.XDW_OPEN_UPDATE


class AuthMode(IntEnum):
    NONE = C.XDW_AUTH_NONE
    NO_DIALOG = C.XDW_AUTH_NODIALOGUE
    CONDITIONAL_DIALOG = C.XDW_AUTH_CONDITIONAL_DIALOGUE


class AnnotationType(IntEnum):
    OLE = C.XDW_AID_OLE
    TEXT = C.XDW_AID_TEXT
    STICKY = C.XDW_AID_FUSEN
    MARKER = C.XDW_AID_MARKER
    DATE_STAMP = C.XDW_AID_STAMP
    STRAIGHT_LINE = C.XDW_AID_STRAIGHTLINE
    RECTANGLE = C.XDW_AID_RECTANGLE
    ELLIPSE = C.XDW_AID_ARC
    BITMAP = C.XDW_AID_BITMAP
    POLYGON = C.XDW_AID_POLYGON
    CUSTOM = C.XDW_AID_CUSTOM
    TITLE = C.XDW_AID_TITLE
    GROUP = C.XDW_AID_GROUP
    LINK = C.XDW_AID_LINK
    PAGE_FORM = C.XDW_AID_PAGEFORM


class AttributeType(IntEnum):
    INT = C.XDW_ATYPE_INT
    STRING = C.XDW_ATYPE_STRING
    DATE = C.XDW_ATYPE_DATE
    BOOL = C.XDW_ATYPE_BOOL
    OCTETS = C.XDW_ATYPE_OCTS
    OTHER = C.XDW_ATYPE_OTHER


class Color(IntEnum):
    NONE = C.XDW_COLOR_NONE
    BLACK = C.XDW_COLOR_BLACK
    RED = C.XDW_COLOR_RED
    GREEN = C.XDW_COLOR_GREEN
    BLUE = C.XDW_COLOR_BLUE
    YELLOW = C.XDW_COLOR_YELLOW
    WHITE = C.XDW_COLOR_WHITE
    GRAY = C.XDW_COLOR_GRAY
    MAROON = C.XDW_COLOR_MAROON
    OLIVE = C.XDW_COLOR_OLIVE
    NAVY = C.XDW_COLOR_NAVY
    PURPLE = C.XDW_COLOR_PURPLE
    TEAL = C.XDW_COLOR_TEAL
    SILVER = C.XDW_COLOR_SILVER
    LIME = C.XDW_COLOR_LIME
    FUCHIA = C.XDW_COLOR_FUCHIA
    AQUA = C.XDW_COLOR_AQUA
    STICKY_RED = C.XDW_COLOR_FUSEN_RED
    STICKY_BLUE = C.XDW_COLOR_FUSEN_BLUE
    STICKY_YELLOW = C.XDW_COLOR_FUSEN_YELLOW
    STICKY_LIME = C.XDW_COLOR_FUSEN_LIME


class BorderType(IntEnum):
    SOLID = C.XDW_BORDER_TYPE_SOLID
    DOT = C.XDW_BORDER_TYPE_DOT
    DASH = C.XDW_BORDER_TYPE_DASH
    DASH_DOT = C.XDW_BORDER_TYPE_DASHDOT
    DOUBLE = C.XDW_BORDER_TYPE_DOUBLE


class ArrowheadType(IntEnum):
    NONE = C.XDW_LINE_NONE
    BEGINNING = C.XDW_LINE_BEGINNING
    ENDING = C.XDW_LINE_ENDING
    BOTH = C.XDW_LINE_BOTH


class ArrowheadStyle(IntEnum):
    WIDE_POLYLINE = C.XDW_LINE_WIDE_POLYLINE
    POLYLINE = C.XDW_LINE_POLYLINE
    POLYGON = C.XDW_LINE_POLYGON


class LinkType(IntEnum):
    THIS_DOCUMENT = C.XDW_LT_LINK_TO_ME
    XDW = C.XDW_LT_LINK_TO_XDW
    URL = C.XDW_LT_LINK_TO_URL
    OTHER_FILE = C.XDW_LT_LINK_TO_OTHERFILE
    MAIL_ADDRESS = C.XDW_LT_LINK_TO_MAILADDR


class LinkPageFrom(IntEnum):
    XDW = C.XDW_PF_XDW
    BINDER = C.XDW_PF_XBD
    XDW_IN_BINDER = C.XDW_PF_XDW_IN_XBD
